(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const u of i.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();const L="54456765-7aefd8f5a237c404a5d30e560",w="https://pixabay.com/api/";async function f(e,o=1){const r={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await axios.get(w,{params:r})).data}let n;function m(e){const o=document.querySelector(".gallery"),r=e.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        <div class="image-info">
          <p class="info-item"><b>Likes:</b> ${s.likes}</p>
          <p class="info-item"><b>Views:</b> ${s.views}</p>
          <p class="info-item"><b>Comments:</b> ${s.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${s.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");o.insertAdjacentHTML("beforeend",r),n?n.refresh():n=new SimpleLightbox(".gallery a",{captionsData:"alt",captionDelay:250})}function S(){const e=document.querySelector(".gallery");e.innerHTML="",n&&(n.destroy(),n=null)}function h(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}function p(){document.querySelector(".load-more").classList.remove("hidden")}function l(){document.querySelector(".load-more").classList.add("hidden")}const g=document.querySelector(".search-form"),v=document.querySelector(".load-more");let a=1,b="",c=0;const d=15;g.addEventListener("submit",q);v.addEventListener("click",B);async function q(e){e.preventDefault();const o=g.elements.searchQuery.value.trim();if(!o){iziToast.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}b=o,a=1,l(),S(),h();try{const r=await f(o,a);if(r.hits.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c=r.totalHits,m(r.hits),r.hits.length>=d&&a*d<c?p():(l(),a*d>=c&&r.hits.length>0&&iziToast.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}))}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}async function B(){a++,h(),l();try{const e=await f(b,a);m(e.hits);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),a*d>=c?(l(),iziToast.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):p()}catch{iziToast.error({title:"Error",message:"Failed to load more images",position:"topRight"})}finally{y()}}l();
//# sourceMappingURL=index.js.map
